### ISSUE TITLE
[Feature Request] Export and save the environment information before and after upgrade

### ISSUE THREAD

**Issue by biplobice** [concrete5cojp/concrete5-upgrade-shell#16]
Run the concrete/bin/concrete5 c5:info and save the output somewhere.

**Comment by deek87** [comment]
Can you be a bit more specific?
Concrete5 environment info? or what exactly?

**Comment by biplobice** [comment]
Yes. Run the concrete/bin/concrete5 c5:info and save the output somewhere.

**Comment by deek87** [comment]
concrete/bin/concrete5 c5:info doesn't exist pre version 8. So we cant run it before version 8.0.0
